name: Scheduled Python Worker

on:
  schedule:
    - cron: "0 17 */2 * *"
  workflow_dispatch:

jobs:
  run-worker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run Python Script
        run: poetry run uv run src/main.py

      - name: Commit and Push
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "chore: update plugins.json"
          git push